### PR TITLE
update reservation parser to use newer openapi :_end var name

### PR DESCRIPTION
**Pull request by lindgrenj6**
ingress_api-client reference: [/lib/topological_inventory-ingress_api-client/models/reservation.rb#L19](https://github.com/RedHatInsights/topological_inventory-ingress_api-client-ruby/blob/f043d137547711b5924635901ef53317a54efd33/lib/topological_inventory-ingress_api-client/models/reservation.rb#L19)

### CODE REVIEW

**Comment by lindgrenj6** [comment]
seeing a parsing failure when trying to collect in CI - this will fix it.

**Comment by lindgrenj6** [comment]
cc @syncrou @gmcculloug @slemrmartin

**Review by gmcculloug — APPROVED** [review]
Merging so we can test fix in CI

**Review by syncrou — COMMENTED** [review]
LGTM 👍

**Pull request merged**
